# Generated by Django 3.0.3 on 2020-05-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0003_friend_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Room'),
        ),
    ]
